spring:
  application:
    name: construcao-saas

  security:
    user:
      name: arielle

  datasource:
    url: jdbc:postgresql://localhost:5432/arielledb
    username: arielle
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

server:
  port: 8080
